server:
  port: 8081

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false
    username: root
    password: Root1234
    useSSL: true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update